#!/bin/sh
#
# Pipe standard input (or specified files) to the remote printer.
# Accepts all the cat(1) options.
# Can be used with a modified putty client to pipe output to the
# Windows clipboard.  See <http://www.spinellis.gr/sw/windows/puttyclip>.
# Updated version: <https://github.com/jdelkins/puttyclip>
#
# Written by Diomidis Spinellis, July 2003.
# This script is hereby placed into the public domain.
#
# Modified to support tmux by Joel Elkins <joel@elkins.com>, March 2016

# Start remote printing
if [[ -z "$TMUX" ]]; then
	echo -ne "\e[5i"
else
	echo -ne "\ePtmux;\e\e[5i"
fi

# Copy standard input or specified files to the remote printer.
cat $*

# End remote printing
if [[ -z "$TMUX" ]]; then
	echo -ne "\e[4i"
else
	echo -ne "\e\e[4i\e\\"
fi
